// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wufdrmkmndybhjxdstaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1ZmRybWttbmR5YmhqeGRzdGF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTM1NzAsImV4cCI6MjA2NTQ2OTU3MH0.Xd2VUCybceaa8CLQ_pggFBhPyyCLil0nrjUKhHELlN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);